name: Check URLs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: urls-checker-code
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: sphinx_runpython
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 2
        retry_count# : 2
        exclude_urls: http://www.some_url.com
        exclude_patterns: https://dumps.wikimedia.org/
        # force_pass : true

    - name: urls-checker-docs
      uses: urlstechie/urlchecker-action@master
      with:
        subfolder: _doc
        file_types: .md,.py,.rst,.ipynb
        print_all: false
        timeout: 2
        retry_count# : 2
        # exclude_urls: https://github, ...
        # exclude_patterns:
        # force_pass : true
