name: Documentation

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build documentation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: python -m pip install -r requirements.txt

      - name: Install requirements-dev.txt
        run: python -m pip install -r requirements-dev.txt

      - name: Install
        run: python -m pip install -e .

      - id: documentation
        name: Documentation
        run: python -m sphinx ./_doc ./dist/html -n >> "$GITHUB_OUTPUT"

      - name: Echo 3
        run: |
          echo "-------------"
          echo "${{ steps.documentation.outputs.test }}"
          echo "-------------"

      - name: Echo 4
        run: |
          echo "-------------"
          echo "${{join(steps.documentation.outputs.*, '\n')}}"
          echo "-------------"

      - name: Check Errors
        if: contains(steps.documentation.outputs.*, 'ERROR')
        run: |
          echo "Sphinx output has errors."
          exit 1

      - name: Check Warnings
        if: contains(steps.documentation.outputs.*, 'WARNING')
        run: |
          echo "Sphinx output has warnings."
          exit 1

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/html/**
