name: Spell Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install codespell
      - name: Install codespell
        run: pip install codespell

      # Run codespell
      - name: Run codespell
        run: codespell --skip="*.png,*.jpg,*.jpeg,*.gif,*.svg,*.ico,*.pdf,*.js,*.css,*.map,./_unittests/ut__main/data/*,./_doc/api/quote.rst,./sphinx_runpython/language.py" --ignore-words-list="nd,te,OT" --check-filenames
