name: Build Any Wheel

on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: build wheel
        run: python -m pip wheel .

      - uses: actions/upload-artifact@v3
        with:
          path: ./sphinx_runpython*.whl
